services:
    anvil:
        image: ghcr.io/foundry-rs/foundry:latest
        container_name: anvil
        networks:
            - demo
        ports:
            - "8545:8545"
        command: ["anvil --host 0.0.0.0  --state /usr/src/app/.foundrycache"]
        healthcheck:
            test: ["CMD-SHELL", "nc -z 127.0.0.1 8545 || exit 1"]
            interval: 10s
            timeout: 10s
            retries: 3

    deployer:
        image: ghcr.io/foundry-rs/foundry:latest
        container_name: deployer
        depends_on:
            anvil:
                condition: service_healthy
        environment:
            RPC_URL: http://anvil:8545
        networks:
            - demo
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        env_file: "./apps/blockchain/.env"
        command:
            [
                "forge script script/DeployContracts.s.sol --rpc-url $RPC_URL --broadcast --private-key $DEPLOYER_PRIVATE_KEY",
            ]

networks:
    demo:
        name: demo
